### ISSUE TITLE
косячки

### ISSUE THREAD

**Issue by sevon06** [hectep/fogstream_practice#3]
https://github.com/hectep/fogstream_practice/blob/ba5120d909937787991540abef2dde419e97631a/p3/files_v2.py#L14
Что будет в случае отсутствия файла?

https://github.com/hectep/fogstream_practice/blob/ba5120d909937787991540abef2dde419e97631a/p3/files_v2.py#L15
Весь код ниже происходит в открытом файле. Зачем? Не проще будет один раз открыть, прочитать его и закрыть?

https://github.com/hectep/fogstream_practice/blob/ba5120d909937787991540abef2dde419e97631a/p3/files_v2.py#L18
Зачем приводить `map` к `list`? В python3 `map` - это генератор. Егор должен был рассказывать, что генераторы дешевле по памяти, чем итераторы.
Так же, можно избавиться от `map` и `except` переписав на list comprehension. Перехват ошибок дело благородное, но если можно написать без конструкции `try:..except:`, то лучше писать без нее.

https://github.com/hectep/fogstream_practice/blob/ba5120d909937787991540abef2dde419e97631a/p3/files_v2.py#L28
Почему тут может быть `TypeError`? Кодом выше, ты делал `map(int, row)` добавлял в `input_list` только строки с цифрами. По идее тут должны быть только цифры.

https://github.com/hectep/fogstream_practice/blob/ba5120d909937787991540abef2dde419e97631a/p3/files_v2.py#L30
Вызовы функций так не переносят. Почитай pep про перенос строк.

https://github.com/hectep/fogstream_practice/blob/ba5120d909937787991540abef2dde419e97631a/p3/files_v2.py#L32
А `IndexError` то откуда тут может взяться? Ты же итерируешься по списку. Цикл закончится, когда закончится список.

**Comment by hectep** [comment]
@sevon06 Привет! Спасибо за фидбек. Постарался исправить.

`except IndexError:` Нужен для отлова строк, где меньше четырех чисел (приведен в примере), т.е. он ловится во вложенных листах.

Убрал `list(map(int, row)) `, но немного не понял, в чем состояла ошибка. Например  [тут](http://book.pythontips.com/en/latest/map_filter.html#map) так его и юзают. Можешь пояснить?

 Алсо
> Перехват ошибок дело благородное, но если можно написать без конструкции try:..except:, то лучше писать без нее.

Можно как-то ловить ошибки другим способом?

В collaborators ты уже есть, по крайней мере ты мержил ПР от предыдущей задачи. В следующий раз буду делать ПР.

[Спасибо!](https://img.devrant.com/devrant/rant/r_590222_3Ft8m.jpg)

**Comment by sevon06** [comment]
> except IndexError: Нужен для отлова строк, где меньше четырех чисел (приведен в примере), т.е. он ловится во вложенных листах.

Тут можно избежать перехвата ошибки, отфильтровав все вложенные списки по длине меньше 4.

> Убрал list(map(int, row)), но немного не понял, в чем состояла ошибка. Например тут так его и юзают. Можешь пояснить?

`map` модифицирует объекты в списке содержащем данные, к которым можно применить функцию, которая гарантирует, что она выполнится и не упадет. Если ты обвешиваешь это перехватом ошибок, значит ты что-то не так делаешь.

>Можно как-то ловить ошибки другим способом?

Можно просто избегать их.
Например у тебя есть словарь `my_dict = {'foo': 'bar'}`. И обращаясь по ключу `my_dict['foo']` ты будешь получать значение. Но если ты обратишься к несуществующему ключу, например `my_dict['baz']`, то упадет `KeyError`. Чтобы этого избежать нужно использовать конструкцию `my_dict.get('baz')`, которая вернет `None` по умолчанию, если ключ отсутствует в словаре. 
В следующий раз, когда будешь писать код и будет валиться ошибка, подумай не над тем, как перехватить ее, а как написать код, чтобы эта ошибка не появлялась.

Теперь, что касается новых косяков)
https://github.com/hectep/fogstream_practice/blob/f0ad2056d82e0e1e154597a6bd3ed47cda3dcf18/p3/files_v2.py#L18
Можно использовать `readlines`.

В целом у тебя логика не совсем корректна. Ты сначала отсекаешь все строки и сразу пытаешься посчитать получившиеся координаты, и уже при их подсчете ты вылавливаешь то, что их может быть меньше 4. Почему бы сначала не отсечь невалидные координаты и потом уже работать только с валидными?

**Comment by hectep** [comment]
@sevon06 Спасибо за оперативность! Исправил.

**Comment by sevon06** [comment]
https://github.com/hectep/fogstream_practice/blob/1857a5890c65c06d7cb2323c526a4913897ebe5a/p3/files_v2.py#L27
Сюда добавь условие и тогда можно будет избавиться от `try except`

**Comment by hectep** [comment]
@sevon06 Добавил условие, но мне кажется  try-catch более элегантно выглядел.

**Comment by sevon06** [comment]
Хм, да, чет я не углядел, что `'-1'.istigit() == False`. Ок, возвращай тогда `map` обратно.

**Comment by hectep** [comment]
@sevon06 Done
