### ISSUE TITLE
Ревью

### ISSUE THREAD

**Issue by egpro** [hectep/fogstream_practice#8]
https://github.com/hectep/fogstream_practice/blob/c3e5b4903429a6c629fb7ac0db121ab9f8b98d3b/p8/first_project/first_project/my_app/models.py#L1

В моделях необходимо:
1. Указывать мета информацию, такую как стровое представление в ```verbose_name```
2. В каждом поле первым параметром необходимо задавать ```verbose_name``` , для читаемого отображения в админке
3. Когда задаем поле типа внешний ключ, рекомендуется задавать еще и ```related_name```

**Comment by hectep** [comment]
done
